### ISSUE TITLE
Unable to add routes/waypoints

### ISSUE THREAD

**Issue by mmaddex** [SignalK/freeboard-sk#116]
I'm running Signal K `2.0.0`, freeboard-sk `2.0.1`.

I'm able to add/save/retrieve note resources, however trying to add any other type fails with 

```
ERROR TypeError: crypto.randomUUID is not a function
    at get uuid [as uuid] (main.3ccffb5b54c839e3.js:1:806125)
    at i.buildRoute (main.3ccffb5b54c839e3.js:1:1174905)
    at i.showRouteNew (main.3ccffb5b54c839e3.js:1:1177937)
    at i.handleDrawEnd (main.3ccffb5b54c839e3.js:1:2115387)
    at main.3ccffb5b54c839e3.js:1:2133606
    at pS (main.3ccffb5b54c839e3.js:1:78813)
    at Object.s [as next] (main.3ccffb5b54c839e3.js:1:78951)
    at U.__tryOrUnsub (main.3ccffb5b54c839e3.js:1:5053)
    at U.next (main.3ccffb5b54c839e3.js:1:4294)
    at ue._next (main.3ccffb5b54c839e3.js:1:3489)
``` 

Worth noting I get the same error trying to import a GPX file.

Browser: Brave Version 1.52.122 Chromium: 114.0.5735.110 (Official Build) (x86_64)

Video of error https://youtu.be/8e87Yvr8eTY

All installed plugins
<img width="994" alt="image" src="https://github.com/SignalK/freeboard-sk/assets/4720963/bd6cec0e-9cd0-40dc-a113-58a0ef286703">

**Comment by rgregg** [comment]
I'm seeing this on Chrome Version 114.0.5735.133 as well.

**Comment by panaaj** [comment]
I will issue a fix.

**Comment by rgregg** [comment]
Confirming this issue is fixed in the new update. Thanks @panaaj
